// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Address struct {
	ID          int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Name        string
	Street      string
	Suburb      string
	State       string
	Postcode    string
	Country     string
	ReferralsID uuid.UUID
}

type Referral struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Surname   string
	Email     string
	Phone     string
	Avatar    sql.NullString
	Filename  sql.NullString
}
